[server]
address = "127.0.0.1"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#007f83"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f2f6f8"
textColor = "#24354b"
font = "sans serif"
